# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details

name: slurm
version: 23.11.1
summary: "Slurm: A Highly Scalable Workload Manager"
description: |
  Slurm is an open source, fault-tolerant, and highly scalable cluster
  management and job scheduling system for large and small Linux clusters.
license: Apache-2.0
website: "https://slurm.schedmd.com"

base: core22
confinement: classic
compression: lzo
package-repositories:
  - type: apt
    ppa: ubuntu-hpc/rocm-smi-lib
environment:
  # Need this PATH declaration so that the Python-based
  # snap hooks can find the embedded Python interpreter with
  # the necessary dependencies packaged in `site-packages`.
  # yamllint disable-line rule:line-length
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/local/bin:$SNAP/usr/local/sbin:$PATH

apps:
  slurmctld:
    command: sbin/slurmctld.wrapper
    daemon: simple
    install-mode: disable
    after: [munged]
  slurmd:
    command: sbin/slurmd.wrapper
    daemon: simple
    install-mode: disable
    after: [munged]
  slurmdbd:
    command: sbin/slurmdbd.wrapper
    daemon: simple
    install-mode: disable
    after: [munged]
  slurmrestd:
    command: sbin/slurmrestd.wrapper
    daemon: simple
    install-mode: disable
    after: [munged]
  sacct:
    command: bin/sacct
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sacctmgr:
    command: bin/sacctmgr
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  salloc:
    command: bin/salloc
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sattach:
    command: bin/sattach
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sbatch:
    command: bin/sbatch
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sbcast:
    command: bin/sbcast
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  scancel:
    command: bin/scancel
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  scontrol:
    command: bin/scontrol
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  scrontab:
    command: bin/scrontab
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  scrun:
    command: bin/scrun
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sdiag:
    command: bin/sdiag
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sh5util:
    command: bin/sh5util
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sinfo:
    command: bin/sinfo
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sprio:
    command: bin/sprio
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  squeue:
    command: bin/squeue
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sreport:
    command: bin/sreport
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  srun:
    command: bin/srun
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sshare:
    command: bin/sshare
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sstat:
    command: bin/sstat
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  strigger:
    command: bin/strigger
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf
  sview:
    command: bin/sview
    environment:
      SLURM_CONF: $SNAP_COMMON/etc/slurm/slurm.conf

  munged:
    command: sbin/munged.wrapper
    daemon: simple
  munge:
    command: usr/bin/munge --socket $SNAP_COMMON/var/run/munge/munged.socket.2
  unmunge:
    command: usr/bin/unmunge --socket $SNAP_COMMON/var/run/munge/munged.socket.2
  remunge:
    command: usr/bin/remunge --socket $SNAP_COMMON/var/run/munge/munged.socket.2
  mungekey:
    command: usr/sbin/mungekey

parts:
  slurm:
    plugin: autotools
    # yamllint disable-line rule:line-length
    source: "https://download.schedmd.com/slurm/slurm-${SNAPCRAFT_PROJECT_VERSION}.tar.bz2"
    source-type: tar
    build-attributes: [enable-patchelf]
    build-packages:
      - libmunge-dev
      - libncurses-dev
      - libgtk2.0-dev
      - default-libmysqlclient-dev
      - libpam0g-dev
      - libperl-dev
      - libpam0g-dev
      - liblua5.4-dev
      - libhwloc-dev
      - librrd-dev
      - libipmimonitoring-dev
      - hdf5-helpers
      - libfreeipmi-dev
      - libhdf5-dev
      - man2html
      - libcurl4-openssl-dev
      - libpmix-dev
      - libhttp-parser-dev
      - libyaml-dev
      - libjson-c-dev
      - libjwt-dev
      - liblz4-dev
      - bash-completion
      - libdbus-1-dev
      - librdkafka-dev
      - librocm-smi-dev
      - libibmad-dev
      - libibumad-dev
      - libnuma-dev
      - libaec-dev
    stage-packages:
      - munge
      - libncurses5
      - libgtk2.0-0
      - libmysqlclient21
      - libpam0g
      - libperl5.34
      - liblua5.4-0
      - libhwloc15
      - librrd8
      - libipmimonitoring6
      - hdf5-helpers
      - libfreeipmi17
      - hdf5-helpers
      - man2html
      - libcurl4
      - libpmix2
      - libhttp-parser2.9
      - libyaml-0-2
      - libjson-c5
      - libjwt0
      - liblz4-1
      - libdbus-1-3
      - librdkafka1
      - librocm-smi64-1
      - libibmad5
      - libibumad3
      - libnuma1
      - libaec0
      - libsz2
      - libhdf5-hl-100
      - libhdf5-103-1
    autotools-configure-parameters:
      - --prefix=/
      - --localstatedir=/var
      - --runstatedir=/var/run/slurm
      - --disable-developer
      - --disable-debug
      - --enable-slurmrestd
      - --enable-multiple-slurmd
      - --with-munge
      - --with-libcurl
      - --with-http-parser
      - --with-yaml
      - --with-json
      - --with-jwt
      - --with-hdf5=yes
      - --with-rdkafka
      - --with-freeipmi
      - --with-ofed
      - --with-pmix

  slurm-overlay:
    after: [slurm]
    plugin: dump
    source: overlays/slurm
    organize:
      "overlays/slurm/sbin/*": sbin/

  munge-overlay:
    after: [slurm]
    plugin: dump
    source: overlays/munge
    organize:
      "overlays/munge/sbin/*": sbin/

  snap-hooks:
    source: .
    build-attributes: [enable-patchelf]
    plugin: python
    build-packages:
      - git
      - python3-setuptools
    python-requirements: [requirements.txt]
    stage-packages:
      - libpython3.10-stdlib
      - libpython3.10-minimal
      - python3-venv
      - python3.10-minimal
    override-build: |
      craftctl default
      snap-helpers write-hooks
